kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: custodian-task
  annotations:
    description: |
      A Cloud Custodian task
spec:
  workspaces:
    - name: source
      description: Build artifacts.
      mountPath: /workspace/source
  params:
    - name: IMAGE
      description: container image to run
      type: string
      default: "85matthew/custodian:latest"
    - name: MODE
      description: custodian mode to run tests
      type: string
      default: "dry-run"

  steps:
    - name: execute
      image: "$(params.IMAGE)"
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        docker-entrypoint.sh $(params.MODE)
