varReference:
  - path: spec/to/name
    kind: Route

  - path: spec/triggers/bindings/ref
    kind: EventListener

  - path: spec/triggers/template/name
    kind: EventListener

  - path: spec/resourcetemplates/spec/serviceAccountName
    kind: TriggerTemplate

  - path: spec/serviceAccountName
    kind: EventListener

  - path: subjects/name
    kind: RoleBinding