apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - config.yaml

vars:
  - name: EVENT_LISTENER
    objref:
      kind: EventListener
      name: eventlistener
      apiVersion: triggers.tekton.dev/v1alpha1

  - name: TRIGGER_BINDING
    objref:
      kind: TriggerBinding
      name: triggerbinding
      apiVersion: triggers.tekton.dev/v1alpha1

  - name: TRIGGER_TEMPLATE
    objref:
      kind: TriggerTemplate
      name: triggertemplate
      apiVersion: triggers.tekton.dev/v1alpha1

  - name: SERVICEACCOUNT_NAME
    objref:
      kind: ServiceAccount
      name: pipeline
      apiVersion: v1


generatorOptions:
  disableNameSuffixHash: true

#patchesStrategicMerge:
#  - serviceaccount.yaml


resources:
  - event-listener.yaml
  - trigger-binding.yaml
  - trigger-route.yaml
  - trigger-template.yaml
  - workspace-build-pvc.yaml
  - serviceaccount.yaml
  - container-build-publish-custodian.yaml
  - custodian-task.yaml
  - task-push-image.yaml
  - condition-master-branch.yaml
#  - serviceaccount.yaml
