kind: ClusterTask
apiVersion: tekton.dev/v1beta1
metadata:
  name: simple-bash-shell
  annotations:
    description: |
      A simple bash shell
spec:
  workspaces:
    - name: build-workspace
      description: Build artifacts.
      mountPath: /workspace/source
  params:
    - name: CONTAINER-IMAGE
      description: container image to run
      type: string
      default: "bash:5"
    - name: COMMAND
      description: bash command to run
      type: string
  steps:
    - name: execute
      image: $(params.CONTAINER-IMAGE)
      workingDir: $(workspaces.build-workspace.path)
      script: |
        #!/usr/bin/env bash
        echo "Executing: $(params.COMMAND)"
        bash -c "$(params.COMMAND)"
